main: info.gomeow.chester.Chester
name: Chester
version: ${project.version}
depend: [GriefPrevention]

permissions:
  chester.*:
    children:
      chester.trigger: true
      chester.log: true
  chester.trigger:
    default: true
  chester.log:
    default: true
